### ISSUE TITLE
Asianfanfic downloading error.

### ISSUE THREAD

**Issue by shiichan** [waylaidwanderer/FicSave#111] opened 2015-12-04 19:41 UTC
I want to address that some of asianfanfic.com's fanfictions aren't able to be downloaded and continually have the "INVALID URL! Please make sure you have pasted the exact link." pop up when entering the link exactly as is and copy/paste. the following are a few I'd like to download and wasn't able to due to the invalid link issue. 
http://www.asianfanfics.com/story/view/52378/1/boyphobic-jihwan-minwoo-niel-romance-taemin-youngmin-kwangmin/18

http://www.asianfanfics.com/story/view/64327/boyphilic-jihwan-minwoo-niel-taemin-you-youngmin-kwangmin/18

http://www.asianfanfics.com/story/view/86479/boymanic-jihwan-minwoo-niel-taemin-you-youngmin-kwangmin

http://www.asianfanfics.com/story/view/355483/less-than-lovers-more-than-friends-b1a4-fluff-jinyoung-romance-you

http://www.asianfanfics.com/story/view/229902/room-service-oneshot-2pm-nichkhun-y-you

http://www.asianfanfics.com/story/view/74851/stranded-with-you-b1a4-jinyoung

and a lot more, I don't know if it's because these are mostly 18+ fics or what, but hopefully we can find a bypass for these!!! Thanks!!!

**Comment by waylaidwanderer** [comment] 2016-01-17 19:03
Duplicate of #112

**Closed by waylaidwanderer** 2016-01-17 19:03 UTC
