### ISSUE TITLE
Not receiving doc

### ISSUE THREAD

**Issue by juliadoan** [waylaidwanderer/FicSave#140] opened 2016-07-15 20:19 UTC
I put in my send to kindle fire email and it says that the email is sent but even after i sync my kindle, i still do not receive my story. Do you know why this is happening and is there any way to fix it?

**Comment by Nonitaa** [comment] 2016-07-17 16:19
The same thing happening to me...I have not made any changes and everything was working as usual..But I have almost a week without receiving anything in mobi format to my Kindle app that I have on my Ipad.
Is there any way to fix that? Why is this happening?
Thanks for the help.

**Comment by waylaidwanderer** [comment] 2016-07-20 16:38
Duplicate of #133

**Closed by waylaidwanderer** 2016-07-20 16:38 UTC
