### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Britt5290** [waylaidwanderer/FicSave#137] opened 2016-07-11 19:22 UTC
No matter what website, fanfiction.net, Hawthorne and vine, adultfanfiction.org or any other sitemembers it will send the email but when I go to open it, it's say file is corrupt or not opening at all.

**Comment by waylaidwanderer** [comment] 2016-07-11 19:44
Duplicate of #133

**Closed by waylaidwanderer** 2016-07-11 19:44 UTC
