### ISSUE TITLE
email not working (see notes below)

### ISSUE THREAD

**Issue by adquintero2230** [waylaidwanderer/FicSave#141] opened 2016-07-18 00:32 UTC
Hi,  
I set up the bookmarklet for the new ficsave.xyz site.  When I attempt to download a story from Fanfiction.net the email that I entered in the bookmarklet has the following example of extra symbols: "myemail@gmail.com"/   This causes a "failure to send email" error message because of the extra symbols.  
IF I try to add a story from the main Ficsave.xyz site and copy/past the story link and use the correct email address format without the symbols.  The email is sent successfully upon completion. HOWEVER, when I attempt to open it for my Kindle Fire, the story does not open.  HELP

**Comment by waylaidwanderer** [comment] 2016-07-20 16:39
Duplicate of #133

**Closed by waylaidwanderer** 2016-07-20 16:39 UTC

**Comment by waylaidwanderer** [comment] 2016-07-24 04:22
Also this has been fixed now.
