### ISSUE TITLE
Asianfanfics Error

### ISSUE THREAD

**Issue by choihyobin** [waylaidwanderer/FicSave#117] opened 2016-01-16 14:27 UTC
Hi. I'm trying to download this fic in AFF (http://www.asianfanfics.com/story/view/782194) 
![screenshot_2016-01-16-22-25-51](https://cloud.githubusercontent.com/assets/16733901/12372850/225c4e12-bca0-11e5-980d-ed82a5bd91de.png) and the "downloading chapter" part is a bit odd since it shows a -1 on it, as shown in the picture, thus it cannot download the entire fic. Hope this gets resolved. Thanks :)

**Comment by waylaidwanderer** [comment] 2016-01-17 19:01
Duplicate of #113

**Closed by waylaidwanderer** 2016-01-17 19:01 UTC
