### ISSUE TITLE
Asianfanfic error 

### ISSUE THREAD

**Issue by blo000** [waylaidwanderer/FicSave#100] opened 2015-10-08 06:11 UTC
http://www.asianfanfics.com/story/view/902523/teach-me-magic-love-infinite-myungsoo-myungyeol-sungyeol-sooyeol-hogwartsau Tried downloading fic to read but it says error and i don't know what's wrong?

**Comment by waylaidwanderer** [comment] 2016-01-17 19:02
Duplicate of #101

**Closed by waylaidwanderer** 2016-01-17 19:02 UTC
