### ISSUE TITLE
Asianfanfic chapter error

### ISSUE THREAD

**Issue by donomique** [waylaidwanderer/FicSave#104] opened 2015-11-08 02:33 UTC
i downloaded two stories (http://www.asianfanfics.com/story/view/211951 and http://www.asianfanfics.com/story/view/498380) from asianfanfics but the file is always incomplete and missing chapters. i tried different formats on different devices but it's always the same error

**Comment by waylaidwanderer** [comment] 2016-01-17 19:03
Duplicate of #111

**Closed by waylaidwanderer** 2016-01-17 19:03 UTC
