### ISSUE TITLE
Adding Summary And Fic Info

### ISSUE THREAD

**Issue by sapo93** [waylaidwanderer/FicSave#42] opened 2014-11-17 16:14 UTC
Not an issue, bu an enanchement request.

It would be nice to give the option to include in the first page the story details, as displayed in the site, such as summary, category, characters, etc.

For Example:

![example](https://cloud.githubusercontent.com/assets/5947905/5072772/0fc00bda-6e7d-11e4-8798-9722f0fc8468.jpg)

**Comment by Liamgrbd** [comment] 2015-07-27 02:23
I second this request. It would be really nice to have all the metadata downloaded too. Namely:

- Summary
- Publish date
- Update date
- Download date
- Genre
- Rating
- Characters
- Word count
- Original link to the story
- Link to the author's profile

**Comment by chikiko** [comment] 2015-07-27 05:35
Please also include language.  Some of us read fanfics in other languages.

**Comment by waylaidwanderer** [comment] 2015-08-15 03:30
This has been added in the latest update, aside from the original link to the story. However, the URL is included in the book's metadata, which you should be able to view using the majority of ebook reader apps.

**Comment by waylaidwanderer** [comment] 2015-08-15 03:30
Duplicate of #38

**Closed** 2015-08-15 03:30 UTC
