### ISSUE TITLE
Not downloading

### ISSUE THREAD

**Issue by sue1zide** [waylaidwanderer/FicSave#97] opened 2015-09-16 09:16 UTC
Nothing will download. I've used the bookmarklet and the actual site yet nothing will download.

**Comment by sanhongseol** [comment] 2015-09-16 14:22
I have the same problem. Nothing is downloading and I've tried various browsers.

**Comment by waylaidwanderer** [comment] 2015-09-16 15:44
Duplicate of #96

**Closed by waylaidwanderer** 2015-09-16 15:44 UTC
