### ISSUE TITLE
Error: Failed to download

### ISSUE THREAD

**Issue by EasyJade** [waylaidwanderer/FicSave#131] opened 2016-07-05 20:15 UTC
Continuously getting the Error: failed to download chapter message. Have tried multiple fan fictions to experiment and all have the same result. They download a few chapters then the error pops up. Any ideas?

**Comment by peterberbec** [comment] 2016-07-05 20:27
Happening to me too. Almost always gets ch. 1, sometimes 2, 3 and 4 (rarely) but that's it.

**Comment by waylaidwanderer** [comment] 2016-07-05 22:01
Duplicate of #130, conversation will continue there.

**Closed by waylaidwanderer** 2016-07-05 22:01 UTC
