### ISSUE TITLE
ASIANFANFICS ERROR

### ISSUE THREAD

**Issue by ficsavingyuju** [waylaidwanderer/FicSave#113] opened 2015-12-10 10:58 UTC
Every time I try and download a fic from AsianFanFics it keeps counting the chapters and says something ridiculous e.g. Downloading chapter 324 of -1, it's always a large number out of -1
PLS FIX thank u :D

**Comment by waylaidwanderer** [comment] 2016-01-17 19:01
Duplicate of #100

**Closed by waylaidwanderer** 2016-01-17 19:01 UTC
