### ISSUE TITLE
Asianfanfic chapter error

### ISSUE THREAD

**Issue by donomique** [waylaidwanderer/FicSave#101] opened 2015-10-12 12:39 UTC
I can only download one chapter from asianfanfics. It says it downloads all the chapters but when I open the file, it only shows the first chapter. Tried all formats on laptop and mobile. Tried editing the link using other chapters for it. http://www.asianfanfics.com/story/view/669951 this is is the fic ^^

**Comment by waylaidwanderer** [comment] 2016-01-17 19:02
Duplicate of #104

**Closed by waylaidwanderer** 2016-01-17 19:02 UTC
