### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Britt5290** [waylaidwanderer/FicSave#138] opened 2016-07-14 16:26 UTC
I wrote previously but apparently my issue was closed with no comment. i continue to have errors when trying to access the site via computer, tablet or cell phone as soon as i open the webpage it stats a user error has occurred. If i do get the story to go through once i get the email and try to download it states the file is corrupt and to delete it no matter what format i try.

**Comment by waylaidwanderer** [comment] 2016-07-20 16:38
Duplicate of #133

**Closed by waylaidwanderer** 2016-07-20 16:38 UTC
